[build]
command = "npm run build"
pages_build_output_dir = ".vercel/output/static"

[env.production]
node_compat = true

[miniflare]
kv_persist = true
cache_persist = true

[rules]
type = "ESModule"
globs = ["**/node_modules/**"]